CREATE TABLE Anunciante (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    CPF CHAR(11) UNIQUE NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    SenhaHash VARCHAR(255) NOT NULL,
    Telefone VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE Anuncio (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Marca VARCHAR(30) NOT NULL,
    Modelo VARCHAR(50) NOT NULL,
    Ano CHAR(4) NOT NULL,
    Cor VARCHAR(30),
    Quilometragem VARCHAR(20),
    Descricao TEXT,
    Valor DECIMAL(12,2) NOT NULL,
    DataHora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Estado VARCHAR(50),
    Cidade VARCHAR(50),
    IdAnunciante INT NOT NULL,
    FOREIGN KEY (IdAnunciante) REFERENCES Anunciante(Id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Foto (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    IdAnuncio INT NOT NULL,
    NomeArqFoto VARCHAR(255) NOT NULL,
    FOREIGN KEY (IdAnuncio) REFERENCES Anuncio(Id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Interesse (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Telefone VARCHAR(20),
    Mensagem TEXT,
    DataHora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IdAnuncio INT NOT NULL,
    FOREIGN KEY (IdAnuncio) REFERENCES Anuncio(Id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;
